services:
  kafka:
    image: imdhruv99/kafka:1.0.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9999:9999"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_NUM_PARTITIONS=5
      - KAFKA_LOG_RETENTION_HOURS=24
      - KAFKA_MESSAGE_MAX_BYTES=2000000
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-logs:/var/lib/kafka/logs
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  kafka-data:
    driver: local
  kafka-logs:
    driver: local

networks:
  kafka-network:
    driver: bridge
